[config]
# ...
[templates.hyprland_conf]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
# ...
[templates.hyprland_lua]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'
# ...
[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'
# ...
[templates.swaync]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"
# ...
[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"
# ...
[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/config'
post_hook = 'pkill -USR1 cava'
# ...
[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'
# ...
[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'
# ...
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"; gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"'

# ...
[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"; gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"'
# ...
