cursor            #8cdb3d
cursor_text_color #1c3700

foreground            #e0e5d3
background            #0b1006
selection_foreground  #1c3700
selection_background  #aad380
url_color             #aad380

#: black 000000 767676
color0  #10150b
color8  #31362b
#: red cc0403 f2201f
color1  #9ca625
color9  #dce381
#: green 19cb00 23fd00
color2  #aad380
color10 #c5f09a
#: yellow cecb00 fffd00
color3  #42dfa7
color11 #65fcc1
#: blue 0d73cc 1a8fff
color4  #2b5000
color12 #8cdb3d
#: magenta cb1ed1 fd28ff
color5  #2e4f0b
color13 #aad380
#: cyan 0dcdcd 14ffff
color6  #005139
color14 #42dfa7
#: white dddddd ffffff
color7  #c1cab2
color15 #e0e5d3

mark1_foreground #0e2000
mark1_background #a7f857
mark2_foreground #0e2000
mark2_background #c5f09a
mark3_foreground #002115
mark3_background #65fcc1

active_tab_foreground #1c3700
active_tab_background #8cdb3d
inactive_tab_foreground #112500
inactive_tab_background #72be1e

active_border_color #8cdb3d
inactive_border_color #1c3700
# bell_border_color #ff5a00
