#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc>
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec = hyprctl dispatch submap global
exec-once = swww-daemon
exec-once = waybar &
exec-once = qs -c overview
exec-once = swww-daemon
exec-once = systemctl --user start hyprpolkitagent
exec-once = swww img ~/.config/hypr/hyprlock_assets/current_wallpaper.jpg
exec-once = hyprctl reload
exec-once = hypridle
