$image = /home/repelente808/Wallpapers/wp12542880-green-desktop-4k-wallpapers.jpg

$background = rgba(10150bff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2d3227ff)

$inverse_primary = rgba(3a6a00ff)

$inverse_surface = rgba(e0e5d3ff)

$on_background = rgba(e0e5d3ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(1c3700ff)

$on_primary_container = rgba(112500ff)

$on_primary_fixed = rgba(0e2000ff)

$on_primary_fixed_variant = rgba(2b5000ff)

$on_secondary = rgba(1c3700ff)

$on_secondary_container = rgba(c7f19bff)

$on_secondary_fixed = rgba(0e2000ff)

$on_secondary_fixed_variant = rgba(2e4f0bff)

$on_surface = rgba(e0e5d3ff)

$on_surface_variant = rgba(c1cab2ff)

$on_tertiary = rgba(003826ff)

$on_tertiary_container = rgba(002618ff)

$on_tertiary_fixed = rgba(002115ff)

$on_tertiary_fixed_variant = rgba(005139ff)

$outline = rgba(8b947eff)

$outline_variant = rgba(414a37ff)

$primary = rgba(8cdb3dff)

$primary_container = rgba(72be1eff)

$primary_fixed = rgba(a7f857ff)

$primary_fixed_dim = rgba(8cdb3dff)

$scrim = rgba(000000ff)

$secondary = rgba(aad380ff)

$secondary_container = rgba(30520dff)

$secondary_fixed = rgba(c5f09aff)

$secondary_fixed_dim = rgba(aad380ff)

$shadow = rgba(000000ff)

$source_color = rgba(72be1eff)

$surface = rgba(10150bff)

$surface_bright = rgba(363b2fff)

$surface_container = rgba(1c2116ff)

$surface_container_high = rgba(272c20ff)

$surface_container_highest = rgba(31362bff)

$surface_container_low = rgba(181d13ff)

$surface_container_lowest = rgba(0b1006ff)

$surface_dim = rgba(10150bff)

$surface_tint = rgba(8cdb3dff)

$surface_variant = rgba(414a37ff)

$tertiary = rgba(42dfa7ff)

$tertiary_container = rgba(00c28cff)

$tertiary_fixed = rgba(65fcc1ff)

$tertiary_fixed_dim = rgba(42dfa7ff)

