###################
### MY PROGRAMS ###
###################
# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$menu = hyprlauncher
#################
###  editing  ###
#################
source= ~/.config/hypr/looknfeel.conf
source= ~/.config/hypr/monitors.conf
source= ~/.config/hypr/env.conf
source= ~/.config/hypr/autostart.conf
source= ~/.config/hypr/perms.conf
source= ~/.config/hypr/input.conf
source= ~/.config/hypr/workspaces.conf
source= ~/.config/hypr/binds.conf
exec-once = hyprctl reload
exec-once = hypridle
# theming
env = QT_QPA_PLATFORMTHEME,gtk3
exec = hyprctl dispatch submap global
exec-once = swww-daemon
submap = global
exec-once = waybar &
disable_splash_rendering = true
disable_hyprland_logo = true
# PrintScreen related things
bind = SUPER SHIFT, S, exec, quickshell -c HyprQuickFrame -n
bind = , Print, exec, grimblast --notify copysave screen
bind = $mainMod SHIFT, T, exec, quickshell -c QuickSnip -n
bind = Super, TAB, exec, qs ipc -c overview call overview toggle
exec-once = qs -c overview
bindr = SUPER, SUPER_L,  exec, pkill rofi || rofi -show drun -show-icons
bind = SUPER, L, exec, hyprlock
bind = SUPER, N, exec, swaync-client -t -sw
layerrule = blur on, match:namespace ^(swaync-control-center)$
layerrule = blur on, match:namespace ^(swaync-notification-window)$
layerrule = blur on, match:namespace ^(logout_dialog)$
layerrule = blur on, match:namespace ^(rofi)$
layerrule = ignore_alpha 0.2, match:namespace ^(swaync-control-center)$
layerrule = ignore_alpha 0.2, match:namespace ^(swaync-notification-window)$
layerrule = ignore_alpha 0.5, match:namespace ^(rofi)$
exec-once = swww-daemon
exec-once = systemctl --user start hyprpolkitagent
exec-once = swww img ~/.config/hypr/hyprlock_assets/current_wallpaper.jpg
windowrule = match:title ^(Picture-in-Picture)$, float 1
windowrule = match:title ^(Picture-in-Picture)$, move 1400 780
windowrule = match:title ^(Picture-in-Picture)$, pin 1        
windowrule = match:title ^(Picture-in-Picture)$, size 512 288
######################
###  User Settings ###
######################
