###################
### MY PROGRAMS ###
###################
# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$menu = hyprlauncher
#################
###  editing  ###
#################
source= ~/.config/hypr/looknfeel.conf
source= ~/.config/hypr/monitors.conf
source= ~/.config/hypr/env.conf
source= ~/.config/hypr/autostart.conf
source= ~/.config/hypr/perms.conf
source= ~/.config/hypr/input.conf
source= ~/.config/hypr/workspaces.conf
source= ~/.config/hypr/binds.conf
source= ~/.config/hypr/rules.conf
######################
###  User Settings ###
######################
exec-once = hyprlock
