-- Generated by nwg-displays on 2026-06-09 at 18:40:59. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@119.88",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@74.97",
    position = "1920x0",
    scale = 1.0
})
