####################
### System Rules ###
####################
layerrule = blur on, match:namespace ^(swaync-control-center)$
layerrule = blur on, match:namespace ^(swaync-notification-window)$
layerrule = blur on, match:namespace ^(logout_dialog)$
layerrule = blur on, match:namespace ^(rofi)$
layerrule = ignore_alpha 0.2, match:namespace ^(swaync-control-center)$
layerrule = ignore_alpha 0.2, match:namespace ^(swaync-notification-window)$
layerrule = ignore_alpha 0.2, match:namespace ^(rofi)$
windowrule = match:title ^(Picture-in-Picture)$, float 1
windowrule = match:title ^(Picture-in-Picture)$, move 1400 780
windowrule = match:title ^(Picture-in-Picture)$, pin 1
windowrule = match:title ^(Picture-in-Picture)$, size 512 288
