####################
### System Rules ###
####################
layerrule = blur on, match:namespace ^(swaync-control-center)$
layerrule = blur on, match:namespace ^(swaync-notification-window)$
layerrule = blur on, match:namespace ^(logout_dialog)$
layerrule = blur on, match:namespace ^(rofi)$
animation = layers, 1, 7, menu_decel, slide right
layerrule = animation slide right, match:namespace ^(swaync-notification-window)$
layerrule = animation slide right, match:namespace ^(swaync-control-center)$
layerrule = animation slide bottom, match:namespace ^(logout_dialog)$
layerrule = animation none, match:namespace ^(hyprlax)$
layerrule = animation slide top, match:namespace ^(waybar)$
layerrule = ignore_alpha 0.2, match:namespace ^(swaync-control-center)$
layerrule = ignore_alpha 0.2, match:namespace ^(swaync-notification-window)$
layerrule = ignore_alpha 0.2, match:namespace ^(rofi)$
layerrule = animation popin, match:namespace ^(rofi)$
layerrule = animation popin, match:namespace ^(hyprpicker)$
windowrule = match:title ^(Picture-in-Picture)$, float 1
windowrule = match:title ^(Picture-in-Picture)$, move 1400 780
windowrule = match:title ^(Picture-in-Picture)$, pin 1
windowrule = match:title ^(Picture-in-Picture)$, size 512 288
