[colors]
background = '#1e212b8e'
black = '#1e212b'
blue = '#9EA0A0'
cursor = '#c6c7ca'
cyan = '#D9CBA3'
foreground = '#c6c7ca'
green = '#A6AECA'
magenta = '#92D8DA'
red = '#DDDDDD'
tabs = '#c6c7ca'
tabs-active = '#F6F8FC'
white = '#c6c7ca'
yellow = '#c6c7ca'
dim-black = '#1e212b8e'
dim-blue = '#9EA0A08e'
dim-cyan = '#D9CBA38e'
dim-foreground = '#c6c7ca8e'
dim-green = '#A6AECA8e'
dim-magenta = '#92D8DA8e'
dim-red = '#DDDDDD8e'
dim-white = '#F6F8FC8e'
dim-yellow = '#c6c7ca8e'
light-black = '#9EA0A0'
light-blue = '#D9CBA3'
light-cyan = '#A6AECA'
light-foreground = '#92D8DA'
light-green = '#DDDDDD'
light-magenta = '#F6F8FC'
light-red = '#c6c7ca'
light-white = '#9EA0A0'
light-yellow = '#D9CBA3'
