[colors.primary]
background = "#1e212b"
foreground = "#c6c7ca"

[colors.cursor]
text = "#1e212b"
cursor = "#c6c7ca"

[colors.vi_mode_cursor]
text = "#1e212b"
cursor = "#c6c7ca"

[colors.search.matches]
foreground = "#1e212b"
background = "#c6c7ca"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#656a7b"
background = "#c6c7ca"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#1e212b"
red = "#9EA0A0"
green = "#D9CBA3"
yellow = "#A6AECA"
blue = "#92D8DA"
magenta = "#DDDDDD"
cyan = "#F6F8FC"
white = "#c6c7ca"

[colors.bright]
black = "#656a7b"
red = "#9EA0A0"
green = "#D9CBA3"
yellow = "#A6AECA"
blue = "#92D8DA"
magenta = "#DDDDDD"
cyan = "#F6F8FC"
white = "#c6c7ca"

[colors.dim]
black = "#c6c7ca"
red = "#9EA0A0"
green = "#DDDDDD"
yellow = "#A6AECA"
blue = "#92D8DA"
magenta = "#D9CBA3"
cyan = "#F6F8FC"
white = "#656a7b"

