--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/repelente808/Imagens/Wallpapers/wallpaper6.jpg"

-- Special
background="#1e212b"
foreground="#c6c7ca"
cursor="#c6c7ca"

-- Colors
color0="#1e212b"
color1="#9EA0A0"
color2="#D9CBA3"
color3="#A6AECA"
color4="#92D8DA"
color5="#DDDDDD"
color6="#F6F8FC"
color7="#c6c7ca"
color8="#656a7b"
color9="#9EA0A0"
color10="#D9CBA3"
color11="#A6AECA"
color12="#92D8DA"
color13="#DDDDDD"
color14="#F6F8FC"
color15="#c6c7ca"
