# Shell variables
# Generated by 'wal'
wallpaper="/home/repelente808/Imagens/Wallpapers/wallpaper6.jpg"

# Special
background='#1e212b'
foreground='#c6c7ca'
cursor='#c6c7ca'

# Colors
color0='#1e212b'
color1='#9EA0A0'
color2='#D9CBA3'
color3='#A6AECA'
color4='#92D8DA'
color5='#DDDDDD'
color6='#F6F8FC'
color7='#c6c7ca'
color8='#656a7b'
color9='#9EA0A0'
color10='#D9CBA3'
color11='#A6AECA'
color12='#92D8DA'
color13='#DDDDDD'
color14='#F6F8FC'
color15='#c6c7ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
