--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/repelente808/Pictures/Wallpapers/wallpaper5.png"

-- Special
background="#12110e"
foreground="#dcd3cc"
cursor="#dcd3cc"

-- Colors
color0="#12110e"
color1="#8B673B"
color2="#896C4E"
color3="#877C74"
color4="#91837A"
color5="#867E80"
color6="#A6978D"
color7="#dcd3cc"
color8="#9a938e"
color9="#8B673B"
color10="#896C4E"
color11="#877C74"
color12="#91837A"
color13="#867E80"
color14="#A6978D"
color15="#dcd3cc"
