# pywal theme for ghostty

background = 1e212b
foreground = c6c7ca
cursor-color = c6c7ca
selection-background = c6c7ca
selection-foreground = 1e212b

palette = 0=#1e212b
palette = 1=#9EA0A0
palette = 2=#D9CBA3
palette = 3=#A6AECA
palette = 4=#92D8DA
palette = 5=#DDDDDD
palette = 6=#F6F8FC
palette = 7=#c6c7ca
palette = 8=#656a7b
palette = 9=#9EA0A0
palette = 10=#D9CBA3
palette = 11=#A6AECA
palette = 12=#92D8DA
palette = 13=#DDDDDD
palette = 14=#F6F8FC
palette = 15=#c6c7ca
